version: '3.8'

services:
  webhook-server:
    build: .
    container_name: webhook-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - VERIFY_TOKEN=YOUR_VERIFY_TOKEN
      - PAGE_ACCESS_TOKEN=YOUR_PAGE_ACCESS_TOKEN